name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: "v1.x"

      - name: Cache Dependencies
        run: deno cache deps.ts

      - name: Format
        run: deno fmt --unstable

      - name: Lint
        run: deno lint --ignore=./public --unstable

      - name: Run Tests
        run: deno test -A --unstable

      - name: Deploy to fly.io
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
